import { NextResponse } from "next/server";
import type { ResultSetHeader, RowDataPacket } from "mysql2/promise";
import { pool } from "@/lib/db";

export const runtime = "nodejs";
type OrderItemInput={id?:number;quantity?:number};
type ProductRow=RowDataPacket&{id:number;sku:string|null;name:string;cash_price:string|number|null;credit_label:string|null;down_payment:string|number|null;installments:number|null;installment_amount:string|number|null;total_credit:string|number|null};
function digits(value:string){return value.replace(/\D/g,"");}
function money(value:number){return new Intl.NumberFormat("es-PY",{maximumFractionDigits:0}).format(value);}
export async function POST(request:Request){const connection=await pool.getConnection();try{const body=await request.json();const customerName=String(body.customerName||"").trim();const customerPhone=digits(String(body.customerPhone||""));const customerCity=String(body.customerCity||"").trim();const notes=String(body.notes||"").trim();const paymentMode=body.paymentMode==="CREDITO"?"CREDITO":"CONTADO";const rawItems=Array.isArray(body.items)?body.items as OrderItemInput[]:[];const normalized=rawItems.map(item=>({id:Number(item.id),quantity:Math.max(1,Math.min(99,Math.trunc(Number(item.quantity)||1)))})).filter(item=>Number.isInteger(item.id)&&item.id>0);if(!customerName||customerPhone.length<8)return NextResponse.json({ok:false,error:"Completá tu nombre y un teléfono válido."},{status:400});if(!normalized.length)return NextResponse.json({ok:false,error:"El carrito está vacío."},{status:400});const ids=[...new Set(normalized.map(item=>item.id))];const placeholders=ids.map(()=>"?").join(",");const[products]=await connection.query<ProductRow[]>(`
SELECT p.id,p.sku,p.name,p.cash_price,cp.label credit_label,cp.down_payment,cp.installments,cp.installment_amount,cp.total_credit
FROM ecommerce_products p LEFT JOIN ecommerce_credit_plans cp ON cp.id=(SELECT id FROM ecommerce_credit_plans WHERE product_id=p.id AND active=1 ORDER BY sort_order,id LIMIT 1)
WHERE p.active=1 AND p.id IN (${placeholders})`,ids);if(products.length!==ids.length)return NextResponse.json({ok:false,error:"Uno de los productos ya no está disponible. Actualizá el carrito."},{status:409});const byId=new Map(products.map(product=>[Number(product.id),product]));let subtotal=0;const items=normalized.map(input=>{const product=byId.get(input.id)!;const cash=Number(product.cash_price||0);const creditTotal=Number(product.total_credit||0)||(Number(product.down_payment||0)+Number(product.installments||0)*Number(product.installment_amount||0));const unitPrice=paymentMode==="CREDITO"&&creditTotal>0?creditTotal:cash;const creditSummary=paymentMode==="CREDITO"&&product.installments?`${Number(product.down_payment||0)>0?`Entrega ${money(Number(product.down_payment))} Gs. + `:""}${product.installments} cuotas de ${money(Number(product.installment_amount||0))} Gs.`:null;subtotal+=unitPrice*input.quantity;return{product,quantity:input.quantity,unitPrice,creditSummary};});await connection.beginTransaction();const[result]=await connection.execute<ResultSetHeader>(`INSERT INTO ecommerce_orders(customer_name,customer_phone,customer_city,customer_notes,payment_mode,subtotal,status,whatsapp_sent)VALUES(?,?,?,?,?,?,'ENVIADO_WHATSAPP',1)`,[customerName,customerPhone,customerCity||null,notes||null,paymentMode,subtotal]);const code=`PC-${String(result.insertId).padStart(6,"0")}`;await connection.execute("UPDATE ecommerce_orders SET order_code=? WHERE id=?",[code,result.insertId]);for(const item of items){await connection.execute(`INSERT INTO ecommerce_order_items(order_id,product_id,sku,product_name,quantity,unit_price,credit_summary,line_total)VALUES(?,?,?,?,?,?,?,?)`,[result.insertId,item.product.id,item.product.sku,item.product.name,item.quantity,item.unitPrice,item.creditSummary,item.unitPrice*item.quantity]);}await connection.commit();const lines=[`Hola PuntoCell, quiero realizar el pedido ${code}.`,``,`Cliente: ${customerName}`,`Teléfono: ${customerPhone}`,customerCity?`Ciudad: ${customerCity}`:"",`Modalidad: ${paymentMode}`,``,`Productos:`,...items.map((item,index)=>`${index+1}. ${item.product.name} x${item.quantity} — ${money(item.unitPrice*item.quantity)} Gs.${item.creditSummary?` (${item.creditSummary})`:""}`),``,`Total referencial: ${money(subtotal)} Gs.`,notes?`Observación: ${notes}`:"",``,`Aguardo confirmación de stock y condiciones.`].filter(Boolean);const salesNumber=digits(process.env.WHATSAPP_SALES_NUMBER||process.env.NEXT_PUBLIC_WHATSAPP_NUMBER||"");const whatsappUrl=salesNumber?`https://wa.me/${salesNumber}?text=${encodeURIComponent(lines.join("\n"))}`:null;return NextResponse.json({ok:true,orderCode:code,whatsappUrl});}catch(error:any){try{await connection.rollback();}catch{}return NextResponse.json({ok:false,error:error?.message||"No se pudo generar el pedido."},{status:500});}finally{connection.release();}}
