import Link from "next/link";
import { PackageOpen } from "lucide-react";
import type { EcommerceProduct } from "@/lib/ecommerce";
import { formatGuaranies } from "@/lib/ecommerce";
import AddToCartButton from "./cart/AddToCartButton";
import StoreIcon, { type StoreIconName } from "./StoreIcon";

function iconFor(product:EcommerceProduct):StoreIconName{const value=`${product.categorySlug} ${product.categoryName}`.toLowerCase();if(value.includes('celular'))return'phone';if(value.includes('tele'))return'tv';if(value.includes('electro')||value.includes('lavado'))return'washer';if(value.includes('audio'))return'audio';if(value.includes('infor')||value.includes('notebook'))return'notebook';return'accessory';}
export default function ProductCard({product}:{product:EcommerceProduct}){const real=product.id>0;const href=real?`/productos/${product.slug}`:'/contact';const cartProduct={id:product.id,slug:product.slug,name:product.name,sku:product.sku,imageUrl:product.mainImageUrl,cashPrice:product.cashPrice,creditPlan:product.creditPlan};return <article className="group min-w-[242px] max-w-[290px] flex-1 snap-start overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><Link href={href} className="relative grid h-52 place-items-center overflow-hidden bg-gradient-to-br from-slate-50 to-blue-50">{product.offer&&<span className="absolute left-3 top-3 z-10 rounded-full bg-rose-600 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-white">Oferta</span>}{product.mainImageUrl?<img src={product.mainImageUrl} alt={product.name} className="h-full w-full object-contain p-4 transition duration-300 group-hover:scale-105"/>:<StoreIcon name={iconFor(product)} className="h-28 w-28 text-slate-400 transition group-hover:scale-105 group-hover:text-blue-500"/>}</Link><div className="p-4"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-blue-600">{product.brand||product.categoryName}</p><Link href={href}><h3 className="mt-2 min-h-12 text-sm font-extrabold leading-5 text-slate-900 group-hover:text-blue-600">{product.name}</h3></Link><p className="mt-1 text-xs text-slate-500">{product.availability==='EN_STOCK'?'Disponible':product.availability==='SIN_STOCK'?'Sin stock':'Consultar disponibilidad'}</p><div className="mt-4 border-t pt-4">{product.oldPrice&&<p className="text-xs font-semibold text-slate-400 line-through">{formatGuaranies(product.oldPrice)}</p>}<p className="mt-1 text-lg font-black">{formatGuaranies(product.cashPrice)}</p>{product.creditPlan&&<p className="mt-1 text-xs font-bold text-emerald-600">{product.creditPlan.downPayment>0?`Entrega ${formatGuaranies(product.creditPlan.downPayment)} + `:''}{product.creditPlan.installments} cuotas de {formatGuaranies(product.creditPlan.installmentAmount)}</p>}</div><div className="mt-4 grid grid-cols-[1fr_auto] gap-2"><Link href={href} className="flex h-11 items-center justify-center rounded-xl border border-slate-200 px-3 text-sm font-bold text-slate-700 hover:border-blue-200 hover:text-blue-600">Ver detalle</Link>{real?<AddToCartButton product={cartProduct} className="h-11 px-3 [&>svg]:m-0"/>:<span className="grid h-11 w-11 place-items-center rounded-xl bg-slate-100 text-slate-400"><PackageOpen className="h-4 w-4"/></span>}</div></div></article>}

