"use client";

import { Check, Edit3, Loader2, PackageOpen, Plus, RotateCcw, Search, Trash2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import AdminImageUpload from "../components/AdminImageUpload";

type Category = { id: number; name: string; active: boolean };
type Product = {
  id: number; categoryId: number | null; categoryName: string; sku: string; externalCode: string;
  name: string; brand: string; shortDescription: string; description: string; specs: Record<string, string>;
  cashPrice: number | null; oldPrice: number | null; stock: number | null; availability: string;
  mainImageUrl: string; featured: boolean; offer: boolean; seasonal: boolean; active: boolean; sortOrder: number;
  creditPlan: null | { label: string; downPayment: number; installments: number; installmentAmount: number };
};
type Form = {
  name: string; sku: string; externalCode: string; categoryId: string; brand: string;
  shortDescription: string; description: string; specsText: string; cashPrice: string; oldPrice: string;
  stock: string; availability: string; mainImageUrl: string; featured: boolean; offer: boolean;
  seasonal: boolean; active: boolean; sortOrder: string; creditLabel: string; downPayment: string;
  installments: string; installmentAmount: string;
};
const emptyForm: Form = { name: "", sku: "", externalCode: "", categoryId: "", brand: "", shortDescription: "", description: "", specsText: "", cashPrice: "", oldPrice: "", stock: "", availability: "CONSULTAR", mainImageUrl: "", featured: false, offer: false, seasonal: false, active: true, sortOrder: "0", creditLabel: "Plan principal", downPayment: "", installments: "", installmentAmount: "" };
const inputClass = "h-11 w-full rounded-xl border border-slate-200 bg-white px-3.5 text-sm outline-none transition focus:border-blue-500 focus:ring-4 focus:ring-blue-500/10";
const labelClass = "grid gap-1.5 text-xs font-bold text-slate-600";
function formatGs(value: number | null) { return value === null ? "Consultar" : `${new Intl.NumberFormat("es-PY", { maximumFractionDigits: 0 }).format(value)} Gs.`; }
function specsToText(specs: Record<string, string>) { return Object.entries(specs || {}).map(([key, value]) => `${key}: ${value}`).join("\n"); }
function textToSpecs(text: string) { return Object.fromEntries(text.split("\n").map((line) => line.trim()).filter(Boolean).map((line) => { const index = line.indexOf(":"); return index > 0 ? [line.slice(0, index).trim(), line.slice(index + 1).trim()] : [line, ""]; })); }

export default function ProductsAdminClient() {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]);
  const [form, setForm] = useState<Form>(emptyForm); const [editingId, setEditingId] = useState<number | null>(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [query, setQuery] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [pRes, cRes] = await Promise.all([fetch("/api/admin/ecommerce/products", { cache: "no-store" }), fetch("/api/admin/ecommerce/categories", { cache: "no-store" })]); const [p, c] = await Promise.all([pRes.json(), cRes.json()]); if (!pRes.ok || !p.ok) throw new Error(p.error || "No se pudieron cargar productos."); if (!cRes.ok || !c.ok) throw new Error(c.error || "No se pudieron cargar categorías."); setProducts(p.products); setCategories(c.categories); } catch (e: any) { setError(e?.message || "No se pudo cargar el catálogo."); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const filtered = useMemo(() => { const terms = query.toLowerCase().trim().split(/\s+/).filter(Boolean); return products.filter((product) => terms.every((term) => `${product.name} ${product.brand} ${product.sku} ${product.categoryName}`.toLowerCase().includes(term))); }, [products, query]);
  function patch<K extends keyof Form>(key: K, value: Form[K]) { setForm((current) => ({ ...current, [key]: value })); }
  function reset() { setForm(emptyForm); setEditingId(null); setMessage(""); setError(""); }
  function edit(product: Product) { setEditingId(product.id); setForm({ name: product.name, sku: product.sku, externalCode: product.externalCode, categoryId: product.categoryId ? String(product.categoryId) : "", brand: product.brand, shortDescription: product.shortDescription, description: product.description, specsText: specsToText(product.specs), cashPrice: product.cashPrice === null ? "" : String(product.cashPrice), oldPrice: product.oldPrice === null ? "" : String(product.oldPrice), stock: product.stock === null ? "" : String(product.stock), availability: product.availability, mainImageUrl: product.mainImageUrl, featured: product.featured, offer: product.offer, seasonal: product.seasonal, active: product.active, sortOrder: String(product.sortOrder), creditLabel: product.creditPlan?.label || "Plan principal", downPayment: product.creditPlan ? String(product.creditPlan.downPayment) : "", installments: product.creditPlan ? String(product.creditPlan.installments) : "", installmentAmount: product.creditPlan ? String(product.creditPlan.installmentAmount) : "" }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); setMessage(""); try { const payload = { ...form, categoryId: form.categoryId || null, specs: textToSpecs(form.specsText) }; const response = await fetch(editingId ? `/api/admin/ecommerce/products/${editingId}` : "/api/admin/ecommerce/products", { method: editingId ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const json = await response.json(); if (!response.ok || !json.ok) throw new Error(json.error || "No se pudo guardar."); setMessage(editingId ? "Producto actualizado correctamente." : "Producto creado correctamente."); setForm(emptyForm); setEditingId(null); await load(); } catch (e: any) { setError(e?.message || "No se pudo guardar el producto."); } finally { setSaving(false); } }
  async function deactivate(product: Product) { if (!window.confirm(`¿Ocultar “${product.name}” de la tienda?`)) return; const response = await fetch(`/api/admin/ecommerce/products/${product.id}`, { method: "DELETE" }); const json = await response.json(); if (!response.ok || !json.ok) setError(json.error || "No se pudo ocultar."); else load(); }
  return <div><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-blue-600">Catálogo</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950">Productos</h1><p className="mt-2 text-sm text-slate-500">Administrá fotografías, precios, crédito y visibilidad.</p></div><button type="button" onClick={reset} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold text-slate-700 hover:bg-slate-50"><Plus className="h-5 w-5" />Nuevo producto</button></div>
    <div className="mt-7 grid items-start gap-6 xl:grid-cols-[430px_1fr]">
      <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white shadow-sm xl:sticky xl:top-24"><div className="border-b border-slate-100 p-5"><h2 className="font-black text-slate-950">{editingId ? "Editar producto" : "Nuevo producto"}</h2><p className="mt-1 text-xs text-slate-500">Los campos con * son obligatorios.</p></div><div className="grid max-h-none gap-4 p-5 xl:max-h-[calc(100vh-190px)] xl:overflow-y-auto">
        <AdminImageUpload value={form.mainImageUrl} onChange={(value) => patch("mainImageUrl", value)} />
        <label className={labelClass}>Nombre del producto *<input required value={form.name} onChange={(e) => patch("name", e.target.value)} className={inputClass} placeholder="Ej. Smart TV Samsung 50 pulgadas" /></label>
        <div className="grid grid-cols-2 gap-3"><label className={labelClass}>Código/SKU<input value={form.sku} onChange={(e) => patch("sku", e.target.value)} className={inputClass} /></label><label className={labelClass}>Marca<input value={form.brand} onChange={(e) => patch("brand", e.target.value)} className={inputClass} /></label></div>
        <label className={labelClass}>Categoría<select value={form.categoryId} onChange={(e) => patch("categoryId", e.target.value)} className={inputClass}><option value="">Sin categoría</option>{categories.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
        <label className={labelClass}>Descripción corta<input value={form.shortDescription} onChange={(e) => patch("shortDescription", e.target.value)} className={inputClass} maxLength={500} /></label>
        <label className={labelClass}>Descripción completa<textarea value={form.description} onChange={(e) => patch("description", e.target.value)} className={`${inputClass} min-h-24 py-3`} /></label>
        <label className={labelClass}>Especificaciones <span className="font-normal text-slate-400">Una por línea: Característica: Valor</span><textarea value={form.specsText} onChange={(e) => patch("specsText", e.target.value)} className={`${inputClass} min-h-24 py-3 font-mono text-xs`} placeholder={'Pantalla: 6,5 pulgadas\nMemoria: 128 GB'} /></label>
        <div className="rounded-2xl bg-blue-50 p-4"><p className="mb-3 text-xs font-black uppercase tracking-wider text-blue-700">Precio contado</p><div className="grid grid-cols-2 gap-3"><label className={labelClass}>Precio actual<input type="number" min="0" step="1" value={form.cashPrice} onChange={(e) => patch("cashPrice", e.target.value)} className={inputClass} /></label><label className={labelClass}>Precio anterior<input type="number" min="0" step="1" value={form.oldPrice} onChange={(e) => patch("oldPrice", e.target.value)} className={inputClass} /></label></div></div>
        <div className="rounded-2xl bg-emerald-50 p-4"><p className="mb-3 text-xs font-black uppercase tracking-wider text-emerald-700">Plan de crédito</p><label className={labelClass}>Nombre del plan<input value={form.creditLabel} onChange={(e) => patch("creditLabel", e.target.value)} className={inputClass} /></label><div className="mt-3 grid grid-cols-3 gap-2"><label className={labelClass}>Entrega<input type="number" min="0" value={form.downPayment} onChange={(e) => patch("downPayment", e.target.value)} className={inputClass} /></label><label className={labelClass}>Cuotas<input type="number" min="0" value={form.installments} onChange={(e) => patch("installments", e.target.value)} className={inputClass} /></label><label className={labelClass}>Monto cuota<input type="number" min="0" value={form.installmentAmount} onChange={(e) => patch("installmentAmount", e.target.value)} className={inputClass} /></label></div></div>
        <div className="grid grid-cols-2 gap-3"><label className={labelClass}>Stock<input type="number" min="0" value={form.stock} onChange={(e) => patch("stock", e.target.value)} className={inputClass} /></label><label className={labelClass}>Disponibilidad<select value={form.availability} onChange={(e) => patch("availability", e.target.value)} className={inputClass}><option value="CONSULTAR">Consultar</option><option value="EN_STOCK">En stock</option><option value="SIN_STOCK">Sin stock</option></select></label></div>
        <div className="grid grid-cols-2 gap-2 rounded-2xl border border-slate-200 p-4">{([['featured','Destacado'],['offer','Oferta'],['seasonal','Temporada'],['active','Publicado']] as [keyof Form,string][]).map(([key, label]) => <label key={key} className="flex items-center gap-2 text-sm font-semibold text-slate-700"><input type="checkbox" checked={Boolean(form[key])} onChange={(e) => patch(key, e.target.checked as never)} className="h-4 w-4 rounded border-slate-300 text-blue-600" />{label}</label>)}</div>
        {error && <p className="rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</p>}{message && <p className="flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700"><Check className="h-4 w-4" />{message}</p>}
        <div className="flex gap-2"><button disabled={saving} className="flex h-11 flex-1 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-bold text-white hover:bg-blue-700 disabled:opacity-60">{saving && <Loader2 className="h-4 w-4 animate-spin" />}{editingId ? "Guardar cambios" : "Crear producto"}</button>{editingId && <button type="button" onClick={reset} className="grid h-11 w-11 place-items-center rounded-xl border border-slate-200"><RotateCcw className="h-4 w-4" /></button>}</div>
      </div></form>
      <section className="min-w-0 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black text-slate-950">Catálogo cargado</h2><p className="text-xs text-slate-500">{filtered.length} de {products.length} productos</p></div><label className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar producto..." className="h-10 w-full rounded-xl border border-slate-200 pl-9 pr-3 text-sm outline-none focus:border-blue-500 sm:w-64" /></label></div>
        {loading ? <div className="grid min-h-64 place-items-center"><Loader2 className="h-7 w-7 animate-spin text-blue-600" /></div> : !filtered.length ? <div className="grid min-h-64 place-items-center p-8 text-center"><div><PackageOpen className="mx-auto h-10 w-10 text-slate-300" /><p className="mt-3 font-bold text-slate-700">Todavía no hay productos</p><p className="mt-1 text-sm text-slate-500">Usá el formulario para cargar el primero.</p></div></div> : <div className="divide-y divide-slate-100">{filtered.map((product) => <article key={product.id} className="flex gap-4 p-4 transition hover:bg-slate-50/70"><div className="grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-2xl bg-slate-100">{product.mainImageUrl ? <img src={product.mainImageUrl} alt="" className="h-full w-full object-contain p-2" /> : <PackageOpen className="h-8 w-8 text-slate-300" />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-black uppercase ${product.active ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{product.active ? "Publicado" : "Oculto"}</span>{product.offer && <span className="rounded-full bg-rose-50 px-2 py-1 text-[10px] font-black uppercase text-rose-600">Oferta</span>}{product.featured && <span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-black uppercase text-blue-600">Destacado</span>}</div><h3 className="mt-2 truncate font-extrabold text-slate-950">{product.name}</h3><p className="mt-1 text-xs text-slate-500">{product.brand || "Sin marca"} · {product.categoryName}</p><div className="mt-3 flex flex-wrap items-end justify-between gap-3"><div><p className="text-lg font-black text-slate-950">{formatGs(product.cashPrice)}</p>{product.creditPlan && <p className="text-xs font-semibold text-emerald-600">{product.creditPlan.installments} cuotas de {formatGs(product.creditPlan.installmentAmount)}</p>}</div><div className="flex gap-2"><button onClick={() => edit(product)} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200 bg-white text-slate-600 hover:border-blue-200 hover:text-blue-600"><Edit3 className="h-4 w-4" /></button><button onClick={() => deactivate(product)} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200 bg-white text-slate-600 hover:border-rose-200 hover:text-rose-600"><Trash2 className="h-4 w-4" /></button></div></div></div></article>)}</div>}
      </section>
    </div>
  </div>;
}
